export const EntityClassMap = {
  workSeriesSchemaBundle: 'WorkSeriesSchemaBundle',
  workSeriesBundleAssignment: 'WorkSeriesBundleAssignment',
  providerRole: 'ProviderRole',
  knowledgeDomain: 'KnowledgeDomain',
  carouselOption: 'CarouselOption',
  knowledgeLevel: 'KnowledgeLevel',
  workTaskType: 'WorkTaskType',
  providerRoleAvailability: 'ProviderRoleAvailability',
  carouselOrder: 'CarouselOrder',
  providerRoleTypeWorkTaskTypeSuitability:
    'ProviderRoleTypeWorkTaskTypeSuitability',
  timeDivision: 'TimeDivision',
  carouselOrderItem: 'CarouselOrderItem',
  asset: 'Asset',
  cycleSubspan: 'CycleSubspan',
  providerRoleType: 'ProviderRoleType',
  serviceCategory: 'ServiceCategory',
  cycleSubspanGroup: 'CycleSubspanGroup',
  assetRoleTypeWorkTaskTypeSuitability: 'AssetRoleTypeWorkTaskTypeSuitability',
  carouselGroupOption: 'CarouselGroupOption',
  carouselGroup: 'CarouselGroup',
  cycle: 'Cycle',
  timeSpan: 'TimeSpan',
  person: 'Person',
  organizationType: 'OrganizationType',
  assetType: 'AssetType',
  workProjectSeriesSchema: 'WorkProjectSeriesSchema',
  carousel: 'Carousel',
  organization: 'Organization'
} as const;
