import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { LibraryProvidersWrapper } from '@/components/providers/LibraryProvidersWrapper';
import React from 'react';
import JoyrideWrapper from '@/components/react-joyride/JoyrideWrapper';
import { steps } from '@/components/react-joyride/steps';
import TooltipSingleton from '@/components/generic/TooltipSingleton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LibraryProvidersWrapper>
          {children}
          <TooltipSingleton />
        </LibraryProvidersWrapper>
        <JoyrideWrapper steps={steps} />
      </body>
    </html>
  );
}
