export const EntityClassMap = {
  buildMetric: 'BuildMetric',
  asset: 'Asset',
  assetRole: 'AssetRole',
  assetRoleAvailability: 'AssetRoleAvailability',
  assetRoleType: 'AssetRoleType',
  assetRoleTypeWorkTaskTypeSuitability: 'AssetRoleTypeWorkTaskTypeSuitability',
  assetType: 'AssetType',
  carousel: 'Carousel',
  carouselGroup: 'CarouselGroup',
  carouselGroupOption: 'CarouselGroupOption',
  carouselOption: 'CarouselOption',
  carouselOrder: 'CarouselOrder',
  carouselOrderItem: 'CarouselOrderItem',
  cycle: 'Cycle',
  cycleSubspan: 'CycleSubspan',
  cycleSubspanGroup: 'CycleSubspanGroup',
  interactionBasedValidation: 'InteractionBasedValidation',
  knowledgeDomain: 'KnowledgeDomain',
  knowledgeLevel: 'KnowledgeLevel',
  knowledgeLevelSeries: 'KnowledgeLevelSeries',
  organization: 'Organization',
  organizationType: 'OrganizationType',
  person: 'Person',
  providerRole: 'ProviderRole',
  providerRoleAvailability: 'ProviderRoleAvailability',
  providerRoleType: 'ProviderRoleType',
  providerRoleTypeWorkTaskTypeSuitability:
    'ProviderRoleTypeWorkTaskTypeSuitability',
  resourceRequirementItem: 'ResourceRequirementItem',
  schedule: 'Schedule',
  staticDeliveryAllocationItem: 'StaticDeliveryAllocationItem',
  timeDivision: 'TimeDivision',
  timeSpan: 'TimeSpan',
  userRole: 'UserRole',
  userRoleType: 'UserRoleType',
  workProjectSeries: 'WorkProjectSeries',
  workProjectSeriesAssignment: 'WorkProjectSeriesAssignment',
  workProjectSeriesMetric: 'WorkProjectSeriesMetric',
  workProjectSeriesSchema: 'WorkProjectSeriesSchema',
  workSchemaNode: 'WorkSchemaNode',
  workSchemaNodeAssignment: 'WorkSchemaNodeAssignment',
  workTaskType: 'WorkTaskType'
} as const;

export type EntityClass = (typeof EntityClassMap)[keyof typeof EntityClassMap];
export {};
