import { EntityTypeMap } from '@/api/entity-type-map';

export const EntityClassMap = {
  buildMetric: 'BuildMetric',
  asset: 'Asset',
  assetRole: 'AssetRole',
  assetRoleAvailability: 'AssetRoleAvailability',
  assetRoleType: 'AssetRoleType',
  assetRoleTypeWorkTaskTypeSuitability: 'AssetRoleTypeWorkTaskTypeSuitability',
  assetType: 'AssetType',
  carousel: 'Carousel',
  carouselGroup: 'CarouselGroup',
  carouselGroupOption: 'CarouselGroupOption',
  carouselOption: 'CarouselOption',
  carouselOrder: 'CarouselOrder',
  carouselOrderSummary: 'CarouselOrderSummary',
  carouselOrderItem: 'CarouselOrderItem',
  cycle: 'Cycle',
  cycleSubspan: 'CycleSubspan',
  cycleSubspanDefinition: 'CycleSubspanDefinition',
  cycleSubspanGroup: 'CycleSubspanGroup',
  initJsonTemplate: 'InitJsonTemplate',
  knowledgeDomain: 'KnowledgeDomain',
  knowledgeLevel: 'KnowledgeLevel',
  knowledgeLevelSeries: 'KnowledgeLevelSeries',
  organization: 'Organization',
  organizationType: 'OrganizationType',
  organizationWorkHierarchy: 'OrganizationWorkHierarchy',
  person: 'Person',
  providerRole: 'ProviderRole',
  providerRoleAvailability: 'ProviderRoleAvailability',
  providerRoleType: 'ProviderRoleType',
  providerRoleTypeWorkTaskTypeSuitability:
    'ProviderRoleTypeWorkTaskTypeSuitability',
  queueTreeNode: 'QueueTreeNode',
  resourceRequirementItem: 'ResourceRequirementItem',
  schedule: 'Schedule',
  staticDeliveryAllocationItem: 'StaticDeliveryAllocationItem',
  timeDivision: 'TimeDivision',
  timeSpan: 'TimeSpan',
  userGuideMarkdown: 'UserGuideMarkdown',
  userRole: 'UserRole',
  userRoleType: 'UserRoleType',
  workProjectSeries: 'WorkProjectSeries',
  workProjectSeriesAssignment: 'WorkProjectSeriesAssignment',
  workProjectSeriesMetric: 'WorkProjectSeriesMetric',
  workProjectSeriesSchema: 'WorkProjectSeriesSchema',
  workSchemaNode: 'WorkSchemaNode',
  workSchemaNodeManualDefinition: 'WorkSchemaNodeManualDefinition',
  workSchemaNodeAssignment: 'WorkSchemaNodeAssignment',
  workTaskType: 'WorkTaskType',
  workTaskTypeName: 'WorkTaskTypeName'
} as const satisfies { [Key in keyof EntityTypeMap]: string };

export type EntityClass = (typeof EntityClassMap)[keyof typeof EntityClassMap];
export {};
