###
POST http://localhost:8080/api/v2/userRoles
Content-Type: application/json

[
  {
    "startDate": "2024-09-12T15:00:01.419Z",
    "knowledgeLevelSeriesId": 2,
    "partyName": "Student, 1",
    "partyType": "PERSON",
    "partyDateOfBirth": "2024-09-12",
    "userRoleType": {
      "name": "Student"
    }
  },  {
    "startDate": "2024-09-12T15:00:01.419Z",
    "knowledgeLevelSeriesId": 2,
    "partyName": "Student, 2",
    "partyType": "PERSON",
    "partyDateOfBirth": "2024-09-12",
    "userRoleType": {
      "name": "Student"
    }
  },  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 3",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 4",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 5",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 6",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 7",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 8",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 9",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 10",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 11",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 12",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 13",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 14",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 15",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
},  {
  "startDate": "2024-09-12T15:00:01.419Z",
  "knowledgeLevelSeriesId": 2,
  "partyName": "Student, 16",
  "partyType": "PERSON",
  "partyDateOfBirth": "2024-09-12",
  "userRoleType": {
    "name": "Student"
  }
}
]

<> 2024-09-12T160331.200.json