###
POST http://localhost:8080/api/v2/schedule/doBuild?cycleId=1
Content-Type: application/json

{
    "autoBuildParametersDto": {
        "multiStepUndoTimeoutMs": 10000,
        "multiUndoIncrement": 5,
        "saveBuild": true,
        "forceSaveMetrics": false
    },
    "costParameters": [
        "ASSET_ABSOLUTE_CONCURRENCY",
        "PARTY_ABSOLUTE_CONCURRENCY",
        "PARTY_CYCLE_SUBSPAN_CONCURRENCY",
        "CAPTIVE_TIME"
    ]
}