###
PUT http://localhost:8080/api/v2/organizations/graphs
Content-Type: application/json

{
  "graphDto": {
    "nodes": [
      {
        "data": {
          "id": 13,
          "name": "All Students",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 13,
            "organizationId": 13,
            "workSchemaNodeId": 27
          }
        },
        "id": 13,
        "distanceFromRoot": 0
      },
      {
        "data": {
          "id": 6,
          "name": "Level 3 Year 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 6,
            "organizationId": 6,
            "workSchemaNodeId": 11
          }
        },
        "id": 6,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 12,
          "name": "Level 3 Year 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 12,
            "organizationId": 12,
            "workSchemaNodeId": 24
          }
        },
        "id": 12,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": -1152921504606846976,
          "name": "Level 4",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": -1152921504606846976,
            "organizationId": -1152921504606846976
          }
        },
        "id": -1152921504606846976,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 4,
          "name": "Keyboard Skills 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 4,
            "organizationId": 4,
            "workSchemaNodeId": 7
          }
        },
        "id": 4,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 10,
          "name": "Keyboard Skills 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 10,
            "organizationId": 10,
            "workSchemaNodeId": 20
          }
        },
        "id": 10,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 3,
          "name": "Aural Skills 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 3,
            "organizationId": 3,
            "workSchemaNodeId": 5
          }
        },
        "id": 3,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 9,
          "name": "Aural Skills 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 9,
            "organizationId": 9,
            "workSchemaNodeId": 18
          }
        },
        "id": 9,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 2,
          "name": "Transcription 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 2,
            "organizationId": 2,
            "workSchemaNodeId": 3
          }
        },
        "id": 2,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 8,
          "name": "Transcription 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 8,
            "organizationId": 8,
            "workSchemaNodeId": 16
          }
        },
        "id": 8,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 5,
          "name": "Composition 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 5,
            "organizationId": 5,
            "workSchemaNodeId": 9
          }
        },
        "id": 5,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 11,
          "name": "Composition 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 11,
            "organizationId": 11,
            "workSchemaNodeId": 22
          }
        },
        "id": 11,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 1,
          "name": "Music Theory 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 1,
            "organizationId": 1,
            "workSchemaNodeId": 1
          }
        },
        "id": 1,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 7,
          "name": "Music Theory 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 7,
            "organizationId": 7,
            "workSchemaNodeId": 14
          }
        },
        "id": 7,
        "distanceFromRoot": 1
      }
    ],
    "closureDtos": [
      {
        "id": 25,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 12,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 1,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 1,
        "target": 1,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 3,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 3,
        "target": 3,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 5,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 5,
        "target": 5,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 7,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 7,
        "target": 7,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 9,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 9,
        "target": 9,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 11,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 11,
        "target": 11,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 13,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 13,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 54,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": -1152921504606846976,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 53,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": -1152921504606846976,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 2,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 2,
        "target": 2,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 4,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 4,
        "target": 4,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 6,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 6,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 8,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 8,
        "target": 8,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 10,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 10,
        "target": 10,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 12,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 12,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 52,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": -1152921504606846976,
        "target": -1152921504606846976,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 55,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": -1152921504606846976,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 14,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 1,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 15,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 2,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 16,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 3,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 17,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 4,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 18,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 5,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 19,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 6,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 20,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 7,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 21,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 8,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 22,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 9,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 23,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 10,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 24,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 11,
        "value": 1,
        "weighting": 1
      }
    ]
  },
  "deletedNodeIdList": [
    0
  ],
  "deletedClosureIdList": [
    0
  ]
}

<> 2024-08-23T140453.200.json