###
POST http://localhost:8080/api/v2/workSchemaNode/knowledgeLevelSeriesGroup
Content-Type: application/json



{
  "knowledgeLevelSeries": {
    "name": "Courses",
    "knowledgeLevelDescriptor": "Course",
    "id": 2,
    "knowledgeLevels": [
      {
        "name": "Level 3 Year 1",
        "id": 4,
        "levelOrdinal": 1,
        "knowledgeLevelSeriesId": 2
      },
      {
        "name": "Level 3 Year 2",
        "id": 5,
        "levelOrdinal": 2,
        "knowledgeLevelSeriesId": 2
      },
      {
        "name": "Level 4",
        "id": 6,
        "levelOrdinal": 3,
        "knowledgeLevelSeriesId": 2
      }
    ]
  },
  "cycle": {
    "id": 1,
    "cycleDayZero": "MONDAY",
    "cycleLengthInDays": 7,
    "cycleLengthInWeeks": 1,
    "maxGroupSize": 4,
    "cycleSubspanGroupSizes": [2, 3, 4, 6, 8]
  },
  "organizationTypeName": "Work Group",
  "children": [
    {
      "knowledgeLevel": {
        "name": "Level 3 Year 1",
        "id": 4,
        "levelOrdinal": 1,
        "knowledgeLevelSeriesId": 2
      },
      "workTaskTypeName": {
        "id": 1,
        "name": "Teaching"
      },
      "children": [
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 19,
                  "name": "Jazz/Pop Voice",
                  "shortCode": "JPV"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/0/0/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/0/0/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/0/0/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/0/0/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(214, 204, 228)"
            }
          ],
          "name": "Student 1",
          "type": "bundle",
          "path": "2/0/0"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 19,
                  "name": "Jazz/Pop Voice",
                  "shortCode": "JPV"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/0/1/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/0/1/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/0/1/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/0/1/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(214, 204, 228)"
            }
          ],
          "name": "Student 2",
          "type": "bundle",
          "path": "2/0/1"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 19,
                  "name": "Jazz/Pop Voice",
                  "shortCode": "JPV"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/0/2/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/0/2/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/0/2/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/0/2/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(214, 204, 228)"
            }
          ],
          "name": "Student 3",
          "type": "bundle",
          "path": "2/0/2"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 20,
                  "name": "Piano",
                  "shortCode": "Pn"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/0/3/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/0/3/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/0/3/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/0/3/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(228, 198, 225)"
            }
          ],
          "name": "Student 4",
          "type": "bundle",
          "path": "2/0/3"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 21,
                  "name": "Classical Voice",
                  "shortCode": "CVo"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/0/4/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/0/4/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/0/4/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/0/4/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(238, 162, 186)"
            }
          ],
          "name": "Student 5",
          "type": "bundle",
          "path": "2/0/4"
        }
      ],
      "path": "2/0",
      "type": "knowledgeLevelGroup"
    },
    {
      "knowledgeLevel": {
        "name": "Level 3 Year 2",
        "id": 5,
        "levelOrdinal": 2,
        "knowledgeLevelSeriesId": 2
      },
      "workTaskTypeName": {
        "id": 1,
        "name": "Teaching"
      },
      "children": [
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 22,
                  "name": "Pop Guitar",
                  "shortCode": "PGt"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/1/0/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/1/0/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/1/0/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/1/0/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(239, 183, 163)"
            }
          ],
          "name": "Student 6",
          "type": "bundle",
          "path": "2/1/0"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 23,
                  "name": "Drum Kit",
                  "shortCode": "DK"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/1/1/0/3/0",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/1/1/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/1/1/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(234, 222, 185)"
            },
            {
              "knowledgeDomains": [
                {
                  "id": 24,
                  "name": "Production",
                  "shortCode": "Pro"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/1/1/1/3/0",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/1/1/1/3",
                  "type": "leafList"
                }
              ],
              "path": "2/1/1/1",
              "type": "knowledgeDomainGroup",
              "color": "rgb(204, 232, 168)"
            }
          ],
          "name": "Student 7",
          "type": "bundle",
          "path": "2/1/1"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 25,
                  "name": "French Horn",
                  "shortCode": "FH"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 8,
                      "path": "2/1/2/0/8/0",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/1/2/0/8",
                  "type": "leafList"
                }
              ],
              "path": "2/1/2/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(166, 235, 175)"
            }
          ],
          "name": "Student 8",
          "type": "bundle",
          "path": "2/1/2"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 24,
                  "name": "Production",
                  "shortCode": "Pro"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/1/3/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/1/3/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/1/3/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/1/3/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(204, 232, 168)"
            }
          ],
          "name": "Student 9",
          "type": "bundle",
          "path": "2/1/3"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 19,
                  "name": "Jazz/Pop Voice",
                  "shortCode": "JPV"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/1/4/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/1/4/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/1/4/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/1/4/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(214, 204, 228)"
            }
          ],
          "name": "Student 10",
          "type": "bundle",
          "path": "2/1/4"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 26,
                  "name": "Double Bass",
                  "shortCode": "Dbl"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/1/5/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/1/5/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/1/5/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/1/5/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(190, 236, 222)"
            }
          ],
          "name": "Student 11",
          "type": "bundle",
          "path": "2/1/5"
        }
      ],
      "path": "2/1",
      "type": "knowledgeLevelGroup"
    },
    {
      "knowledgeLevel": {
        "name": "Level 4",
        "id": 6,
        "levelOrdinal": 3,
        "knowledgeLevelSeriesId": 2
      },
      "workTaskTypeName": {
        "id": 1,
        "name": "Teaching"
      },
      "children": [
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 19,
                  "name": "Jazz/Pop Voice",
                  "shortCode": "JPV"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/2/0/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/2/0/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/2/0/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/2/0/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(214, 204, 228)"
            }
          ],
          "name": "Student 12",
          "type": "bundle",
          "path": "2/2/0"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 27,
                  "name": "Guitar",
                  "shortCode": "Gtr"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/2/1/0/3/0",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/2/1/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/2/1/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(192, 224, 234)"
            },
            {
              "knowledgeDomains": [
                {
                  "id": 24,
                  "name": "Production",
                  "shortCode": "Pro"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/2/1/1/3/0",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/2/1/1/3",
                  "type": "leafList"
                }
              ],
              "path": "2/2/1/1",
              "type": "knowledgeDomainGroup",
              "color": "rgb(204, 232, 168)"
            }
          ],
          "name": "Student 13",
          "type": "bundle",
          "path": "2/2/1"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 24,
                  "name": "Production",
                  "shortCode": "Pro"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/2/2/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/2/2/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/2/2/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/2/2/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(204, 232, 168)"
            }
          ],
          "name": "Student 14",
          "type": "bundle",
          "path": "2/2/2"
        },
        {
          "children": [
            {
              "knowledgeDomains": [
                {
                  "id": 21,
                  "name": "Classical Voice",
                  "shortCode": "CVo"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/2/3/0/3/0",
                      "type": "leaf"
                    },
                    {
                      "size": 3,
                      "path": "2/2/3/0/3/1",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/2/3/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/2/3/0",
              "type": "knowledgeDomainGroup",
              "color": "rgb(238, 162, 186)"
            }
          ],
          "name": "Student 15",
          "type": "bundle",
          "path": "2/2/3"
        },
        {
          "children": [
            {
              "type": "knowledgeDomainGroup",
              "knowledgeDomains": [
                {
                  "id": 21,
                  "name": "Classical Voice",
                  "shortCode": "CVo"
                }
              ],
              "children": [
                {
                  "children": [
                    {
                      "size": 3,
                      "path": "2/2/4/0/3/0",
                      "type": "leaf"
                    }
                  ],
                  "path": "2/2/4/0/3",
                  "type": "leafList"
                }
              ],
              "path": "2/2/4/0",
              "color": "rgb(214, 204, 228)"
            },
            {
              "type": "knowledgeDomainGroup",
              "children": [
                {
                  "path": "2/2/4/1/3",
                  "type": "leafList",
                  "children": [
                    {
                      "path": "2/2/4/1/3/0",
                      "type": "leaf",
                      "size": 3
                    }
                  ]
                }
              ],
              "knowledgeDomains": [
                {
                  "id": 19,
                  "name": "Jazz/Pop Voice",
                  "shortCode": "JPV"
                }
              ],
              "path": "2/2/4/1",
              "color": "rgb(204, 232, 168)"
            }
          ],
          "name": "Student 16",
          "type": "bundle",
          "path": "2/2/4"
        }
      ],
      "path": "2/2",
      "type": "knowledgeLevelGroup"
    }
  ],
  "path": "2",
  "type": "knowledgeLevelSeriesGroup"
}