###
PUT http://localhost:8080/api/v2/organizations/graphs
Content-Type: application/json

{
  "graphDto": {
    "nodes": [
      {
        "data": {
          "id": 13,
          "name": "All Students",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 13,
            "organizationId": 13,
            "workSchemaNodeId": 27
          }
        },
        "id": 13,
        "distanceFromRoot": 0
      },
      {
        "data": {
          "id": 12,
          "name": "Level 3 Year 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 12,
            "organizationId": 12,
            "workSchemaNodeId": 24
          }
        },
        "id": 12,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 6,
          "name": "Level 3 Year 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 6,
            "organizationId": 6,
            "workSchemaNodeId": 11
          }
        },
        "id": 6,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 14,
          "name": "Level 4",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 14,
            "organizationId": 14
          }
        },
        "id": 14,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 15,
          "name": "Xuan",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 15,
            "organizationId": 15,
            "workSchemaNodeId": 37
          }
        },
        "id": 15,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 30,
          "name": "Xie",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 30,
            "organizationId": 30,
            "workSchemaNodeId": 69
          }
        },
        "id": 30,
        "distanceFromRoot": 3
      },
      {
        "data": {
          "id": 16,
          "name": "Yan",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 16,
            "organizationId": 16,
            "workSchemaNodeId": 39
          }
        },
        "id": 16,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 27,
          "name": "Taubaldiyev",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 27,
            "organizationId": 27,
            "workSchemaNodeId": 62
          }
        },
        "id": 27,
        "distanceFromRoot": 3
      },
      {
        "data": {
          "id": 4,
          "name": "Keyboard Skills 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 4,
            "organizationId": 4,
            "workSchemaNodeId": 7
          }
        },
        "id": 4,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 10,
          "name": "Keyboard Skills 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 10,
            "organizationId": 10,
            "workSchemaNodeId": 20
          }
        },
        "id": 10,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 3,
          "name": "Aural Skills 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 3,
            "organizationId": 3,
            "workSchemaNodeId": 5
          }
        },
        "id": 3,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 9,
          "name": "Aural Skills 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 9,
            "organizationId": 9,
            "workSchemaNodeId": 18
          }
        },
        "id": 9,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 20,
          "name": "Chen",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 20,
            "organizationId": 20,
            "workSchemaNodeId": 47
          }
        },
        "id": 20,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 25,
          "name": "Tatianna",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 25,
            "organizationId": 25,
            "workSchemaNodeId": 58
          }
        },
        "id": 25,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 18,
          "name": "Huang",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 18,
            "organizationId": 18,
            "workSchemaNodeId": 43
          }
        },
        "id": 18,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 21,
          "name": "Wang 1",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 21,
            "organizationId": 21,
            "workSchemaNodeId": 49
          }
        },
        "id": 21,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 22,
          "name": "Wang 2",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 22,
            "organizationId": 22,
            "workSchemaNodeId": 52
          }
        },
        "id": 22,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 24,
          "name": "Wang 3",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 24,
            "organizationId": 24,
            "workSchemaNodeId": 56
          }
        },
        "id": 24,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 28,
          "name": "Xiong",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 28,
            "organizationId": 28,
            "workSchemaNodeId": 65
          }
        },
        "id": 28,
        "distanceFromRoot": 3
      },
      {
        "data": {
          "id": 26,
          "name": "Wong",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 26,
            "organizationId": 26,
            "workSchemaNodeId": 60
          }
        },
        "id": 26,
        "distanceFromRoot": 3
      },
      {
        "data": {
          "id": 17,
          "name": "Wu 1",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 17,
            "organizationId": 17,
            "workSchemaNodeId": 41
          }
        },
        "id": 17,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 19,
          "name": "Wu 2",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 19,
            "organizationId": 19,
            "workSchemaNodeId": 45
          }
        },
        "id": 19,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 2,
          "name": "Transcription 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 2,
            "organizationId": 2,
            "workSchemaNodeId": 3
          }
        },
        "id": 2,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 8,
          "name": "Transcription 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 8,
            "organizationId": 8,
            "workSchemaNodeId": 16
          }
        },
        "id": 8,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 5,
          "name": "Composition 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 5,
            "organizationId": 5,
            "workSchemaNodeId": 9
          }
        },
        "id": 5,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 11,
          "name": "Composition 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 11,
            "organizationId": 11,
            "workSchemaNodeId": 22
          }
        },
        "id": 11,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 29,
          "name": "Li",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 29,
            "organizationId": 29,
            "workSchemaNodeId": 67
          }
        },
        "id": 29,
        "distanceFromRoot": 3
      },
      {
        "data": {
          "id": 23,
          "name": "Yu",
          "type": {
            "id": 2,
            "name": "Work Group"
          },
          "workSchemaNodeAssignment": {
            "id": 23,
            "organizationId": 23,
            "workSchemaNodeId": 54
          }
        },
        "id": 23,
        "distanceFromRoot": 2
      },
      {
        "data": {
          "id": 1,
          "name": "Music Theory 1",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 1,
            "organizationId": 1,
            "workSchemaNodeId": 1
          }
        },
        "id": 1,
        "distanceFromRoot": 1
      },
      {
        "data": {
          "id": 7,
          "name": "Music Theory 2",
          "type": {
            "id": 1,
            "name": "Class"
          },
          "workSchemaNodeAssignment": {
            "id": 7,
            "organizationId": 7,
            "workSchemaNodeId": 14
          }
        },
        "id": 7,
        "distanceFromRoot": 1
      }
    ],
    "closureDtos": [
      {
        "id": 3,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 3,
        "target": 3,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 7,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 7,
        "target": 7,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 11,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 11,
        "target": 11,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 30,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 15,
        "target": 15,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 34,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 19,
        "target": 19,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 38,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 23,
        "target": 23,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 42,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 27,
        "target": 27,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 4,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 4,
        "target": 4,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 8,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 8,
        "target": 8,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 12,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 12,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 31,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 16,
        "target": 16,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 35,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 20,
        "target": 20,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 39,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 24,
        "target": 24,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 43,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 28,
        "target": 28,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 28,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 14,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 64,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 20,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 66,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 21,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 67,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 22,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 70,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 23,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 69,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 24,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 65,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 25,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 62,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 26,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 63,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 27,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 72,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 28,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 68,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 29,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 71,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 12,
        "target": 30,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 15,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 1,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 16,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 2,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 17,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 3,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 18,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 4,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 19,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 5,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 20,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 6,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 22,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 7,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 23,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 8,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 24,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 9,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 25,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 10,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 26,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 11,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 27,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 12,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 1,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 1,
        "target": 1,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 5,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 5,
        "target": 5,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 9,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 9,
        "target": 9,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 13,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 13,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 32,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 17,
        "target": 17,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 36,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 21,
        "target": 21,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 40,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 25,
        "target": 25,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 44,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 29,
        "target": 29,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 29,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 14,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 76,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 15,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 85,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 16,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 81,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 17,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 88,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 18,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 80,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 19,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 75,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 20,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 78,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 21,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 79,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 22,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 84,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 23,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 83,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 24,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 77,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 25,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 73,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 26,
        "value": 3,
        "weighting": 1
      },
      {
        "id": 74,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 27,
        "value": 3,
        "weighting": 1
      },
      {
        "id": 87,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 28,
        "value": 3,
        "weighting": 1
      },
      {
        "id": 82,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 29,
        "value": 3,
        "weighting": 1
      },
      {
        "id": 86,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 13,
        "target": 30,
        "value": 3,
        "weighting": 1
      },
      {
        "id": 2,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 2,
        "target": 2,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 6,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 6,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 10,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 10,
        "target": 10,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 14,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 14,
        "target": 14,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 33,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 18,
        "target": 18,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 37,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 22,
        "target": 22,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 41,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 26,
        "target": 26,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 45,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 30,
        "target": 30,
        "value": 0,
        "weighting": 1
      },
      {
        "id": 21,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 14,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 54,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 15,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 58,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 16,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 56,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 17,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 61,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 18,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 89,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 14,
        "target": 26,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 55,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 19,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 90,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 14,
        "target": 27,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 93,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 14,
        "target": 28,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 91,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 14,
        "target": 29,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 92,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 14,
        "target": 30,
        "value": 1,
        "weighting": 1
      },
      {
        "id": 52,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 26,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 53,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 27,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 60,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 28,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 57,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 29,
        "value": 2,
        "weighting": 1
      },
      {
        "id": 59,
        "closureType": "com.futuredyme.Entities.Party.Organization.OrganizationRelationship",
        "source": 6,
        "target": 30,
        "value": 2,
        "weighting": 1
      }
    ]
  },
  "deletedNodeIdList": [
    0
  ],
  "deletedClosureIdList": [
    0
  ]
}

<> 2024-08-23T140453.200.json