###
POST http://localhost:8080/api/v2/providerRoles/createFromRolePostRequestBulk
Content-Type: application/json

[
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Vivaldi",
      "familyName": "Chalmers"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Classical Piano",
              "id": -1,
              "shortCode": "CPo"
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "TUESDAY",
        "startTime": "10:00",
        "endTime": "12:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "THURSDAY",
        "startTime": "10:00",
        "endTime": "12:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Johannes",
      "familyName": "Bruckner"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Piano",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "WEDNESDAY",
        "startTime": "17:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },{
        "day": "THURSDAY",
        "startTime": "17:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Rachel",
      "familyName": "Mahler"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Classical Voice",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "TUESDAY",
        "startTime": "10:00",
        "endTime": "16:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "THURSDAY",
        "startTime": "14:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Sabine",
      "familyName": "Handel"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Production",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "TUESDAY",
        "startTime": "09:00",
        "endTime": "17:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "MONDAY",
        "startTime": "12:00",
        "endTime": "17:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "WEDNESDAY",
        "startTime": "12:00",
        "endTime": "17:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "THURSDAY",
        "startTime": "12:00",
        "endTime": "17:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Ionia",
      "familyName": "Grieg"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Drum Kit",
              "id": -1
            },
            {
              "name": "Production",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "WEDNESDAY",
        "startTime": "10:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "THURSDAY",
        "startTime": "10:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },{
  "baseEntity": {
    "id": 0,
    "dateOfBirth": "1990-09-25",
    "personalName": "FAKE",
    "familyName": "DRUM_TEACHER"
  },
  "suitabilities": [
    {
      "workTaskTypeMatrix": {
        "knowledgeLevelSeriesDtoList": [
          {
            "name": "Courses",
            "id": 2,
            "knowledgeLevels": []
          }
        ],
        "knowledgeDomainDtoInclusionList": [
          {
            "name": "Drum Kit",
            "id": -1
          },
          {
            "name": "Production",
            "id": -1
          }
        ],
        "knowledgeDomainDtoExclusionList": [],
        "workTaskTypeNames": [
          "Teaching"
        ]
      },
      "roleTypeNames": [
        "Teacher"
      ],
      "rating": 1
    }
  ],
  "availabilities": [
    {
      "day": "WEDNESDAY",
      "startTime": "10:00",
      "endTime": "20:00",
      "roleTypeNames": [
        "Teacher"
      ],
      "availabilityCode": "TRUE"
    },
    {
      "day": "THURSDAY",
      "startTime": "10:00",
      "endTime": "20:00",
      "roleTypeNames": [
        "Teacher"
      ],
      "availabilityCode": "TRUE"
    }
  ]
},
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Julian",
      "familyName": "Sibelius"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Guitar",
              "id": -1
            },{
              "name": "Pop Guitar",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "TUESDAY",
        "startTime": "14:15",
        "endTime": "17:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "FRIDAY",
        "startTime": "15:15",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Camille",
      "familyName": "Proust"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "French Horn",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "WEDNESDAY",
        "startTime": "11:00",
        "endTime": "13:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Gustavia",
      "familyName": "Van Beethoven"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Jazz/Pop Voice",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "MONDAY",
        "startTime": "10:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "TUESDAY",
        "startTime": "10:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Jacob",
      "familyName": "Holst"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Double Bass",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "WEDNESDAY",
        "startTime": "11:00",
        "endTime": "12:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "FRIDAY",
        "startTime": "12:00",
        "endTime": "13:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Karol",
      "familyName": "Pope"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "DJ",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "WEDNESDAY",
        "startTime": "17:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  }
]