###
POST http://localhost:8080/api/v2/providerRoles/createFromRolePostRequestBulk
Content-Type: application/json

[
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Vivian",
      "familyName": "Choi"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Classical Piano",
              "id": -1,
              "shortCode": "CPo"
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "TUESDAY",
        "startTime": "10:00",
        "endTime": "12:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "THURSDAY",
        "startTime": "10:00",
        "endTime": "12:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Jamie",
      "familyName": "Brooks"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Piano",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "WEDNESDAY",
        "startTime": "17:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Rebecca",
      "familyName": "Moulton"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Classical Voice",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "TUESDAY",
        "startTime": "10:00",
        "endTime": "16:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "THURSDAY",
        "startTime": "14:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Sarah",
      "familyName": "Hunt"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Production",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "TUESDAY",
        "startTime": "09:00",
        "endTime": "17:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "MONDAY",
        "startTime": "12:00",
        "endTime": "17:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "WEDNESDAY",
        "startTime": "12:00",
        "endTime": "17:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "THURSDAY",
        "startTime": "12:00",
        "endTime": "17:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Ian",
      "familyName": "Griffith"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Drum Kit",
              "id": -1
            },
            {
              "name": "Production",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "WEDNESDAY",
        "startTime": "10:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "THURSDAY",
        "startTime": "10:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Jeremy",
      "familyName": "Sparks"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Guitar",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "MONDAY",
        "startTime": "14:15",
        "endTime": "15:15",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "FRIDAY",
        "startTime": "15:15",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Caroline",
      "familyName": "Prozesky"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "French Horn",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "WEDNESDAY",
        "startTime": "11:00",
        "endTime": "13:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Georgia",
      "familyName": "Van Etten"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Jazz/Pop Voice",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "MONDAY",
        "startTime": "10:00",
        "endTime": "17:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "TUESDAY",
        "startTime": "10:00",
        "endTime": "17:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Joel",
      "familyName": "Humann"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "Double Bass",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "WEDNESDAY",
        "startTime": "11:00",
        "endTime": "12:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      },
      {
        "day": "FRIDAY",
        "startTime": "11:00",
        "endTime": "12:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  },
  {
    "baseEntity": {
      "id": 0,
      "dateOfBirth": "1990-09-25",
      "personalName": "Karla",
      "familyName": "Polk"
    },
    "suitabilities": [
      {
        "workTaskTypeMatrix": {
          "knowledgeLevelSeriesDtoList": [
            {
              "name": "Courses",
              "id": 2,
              "knowledgeLevels": []
            }
          ],
          "knowledgeDomainDtoInclusionList": [
            {
              "name": "DJ",
              "id": -1
            }
          ],
          "knowledgeDomainDtoExclusionList": [],
          "workTaskTypeNames": [
            "Teaching"
          ]
        },
        "roleTypeNames": [
          "Teacher"
        ],
        "rating": 4
      }
    ],
    "availabilities": [
      {
        "day": "WEDNESDAY",
        "startTime": "17:00",
        "endTime": "20:00",
        "roleTypeNames": [
          "Teacher"
        ],
        "availabilityCode": "TRUE"
      }
    ]
  }
]